### ISSUE TITLE
Expand functions to include callouts, headings, and lists w/ new `qto_` naming convention

### ISSUE THREAD

**Issue by elipousson** [ElianHugh/quartools#1]
This package is such an inspiration! Thank you for creating it. Would you be interested in adding a `as_quarto_callout()` function to the package?

I've included a working reprex (using `as_quarto_div()` as a tweaked version of `quartools::div()` and `as_quarto_block()` as a tweaked version of `quartools::as_markdown()`) showing how it could work. These tweaked versions also add support for id values and key value pairs. Let me know if you're interested and I'd be happy to open a pull request.

``` r
`%||%` <- function(x, y) {
  if (rlang::is_null(x)) {
    y
  } else {
    x
  }
}

as_quarto_callout <- function(...,
                              type = c("note", "tip", "warning", "caution", "important"),
                              heading = NULL,
                              collapse = NULL,
                              appearance = NULL,
                              icon = NULL,
                              title = NULL,
                              id = NULL,
                              class = NULL,
                              values = NULL,
                              keys = NULL,
                              level = "##",
                              sep = " ",
                              fence = ":::") {
  type <- rlang::arg_match(type)
  class <- paste0("callout-", type)

  if (is.character(keys) && is.character(values)) {
    values <- rlang::set_names(values, keys)
  }

  stopifnot(is.null(values) || rlang::is_named(values))

  if (!is.null(collapse)) {
    values <- c("collapse" = collapse, values)
  }

  if (!is.null(appearance)) {
    appearance <- rlang::arg_match0(appearance, c("default", "simple", "minimal"))

    values <- c("appearance" = appearance, values)
  }

  if (!is.null(icon)) {
    values <- c("icon" = icon, values)
  }

  if (!is.null(title)) {
    values <- c(values, "title" = title)
  }

  if (is.null(heading)) {
    callout <- as_quarto_div(
      ...,
      class = class,
      id = id,
      values = values,
      fence = fence,
      sep = sep
    )

    return(callout)
  }

  as_quarto_div(
    paste0(level, " ", heading, "\n\n"),
    ...,
    class = class,
    id = id,
    values = values,
    fence = fence,
    sep = sep
  )
}

as_quarto_div <- function(...,
                          class = NULL,
                          id = NULL,
                          values = NULL,
                          keys = NULL,
                          sep = " ",
                          collapse = "",
                          fence = ":::") {
  attr <- div_attributes(id, class, values, keys)

  if (attr != "") {
    attr <- paste0("{", attr, "}")
  }

  as_quarto_block(
    paste0(
      "\n", fence, attr, "\n",
      paste0(..., sep = sep, collapse = collapse),
      "\n", fence, "\n",
      collapse = ""
    )
  )
}

as_quarto_block <- function(..., collapse = "") {
  structure(
    paste0(..., collapse = collapse),
    class = c("knit_asis", "quarto_block")
  )
}

div_attributes <- function(id = NULL,
                           class = NULL,
                           values = NULL,
                           keys = NULL) {
  if (!is.null(id) && !grepl("^#", id)) {
    id <- paste0("#", id)
  }

  if (!is.null(class) && !grepl("^\\.", class)) {
    class <- paste0(".", class)
  }

  if (!is.null(values)) {
    if (rlang::is_named(values)) {
      keys <- keys %||% names(values)
    }

    values <- vapply(
      values,
      \(x) {
        if (is.logical(x)) {
          return(tolower(x))
        }
        paste0("'", x, "'")
      },
      NA_character_
    )

    values <- paste0(keys, "=", values, collapse = " ")
  }

  if (is.null(c(id, class, values))) {
    return("")
  }

  paste0(c(id, class, values), collapse = " ")
}


tip <- as_quarto_callout("Example text.", heading = "With a heading", type = "tip")

print(tip)
#> [1] "\n:::{.callout-tip}\n## With a heading\n\nExample text. \n:::\n"
#> attr(,"class")
#> [1] "knit_asis"    "quarto_block"

note <- as_quarto_callout("- ", c("A", "B", "C"), sep = "\n", type = "note", icon = TRUE)

print(note)
#> [1] "\n:::{.callout-note icon=true}\n- A\n- B\n- C\n\n:::\n"
#> attr(,"class")
#> [1] "knit_asis"    "quarto_block"
```

<sup>Created on 2023-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ElianHugh** [comment]
Hi Eli, thank you for the kind words and the reprex!  Definitely interested in including callouts.

I have a few questions that I'd be interested to hear your thoughts on:

- Is the intention for `as_quarto_div` to replace the current implementation of `quartools::div`? If so, is the naming scheme to avoid namespace collisions with shiny/htmltools? For the "base" markdown elements, I was thinking of distinguishing them from the quarto-specific elements (e.g. `div` vs `with_*` functions)
- I think your idea to use specific parameters for elements is smoother than my current (naive) implementation of using a simple character vector. It also means we can ensure that key-value pairs are in the correct order. Is there a reason why the key-value pairs are separated into two parameters rather than using, say, a named list?

Very happy for you to submit a PR and we take it from there!

---

Incidentally, I've been working on expanding the elements covered from span and div to the broader range of quarto/markdown elements (similar to how `htmltools::tags` handles things), so this suggestion comes at a good time! 

If it's of interest, the current WIP change works off a general element_constructor, but it will require more changes for more complicated elements (such as images). 

```r
element_constructor <- function(template, collapse, attributes, keep_brackets = FALSE) {
    content_expr <- if (!is.null(collapse)) {
        substitute(paste0(dots, collapse = collapse))
    } else {
        substitute(dots)
    }

    function_body <- {
        if (attributes) {
            brackets <- ifelse(keep_brackets, "{}", "")
            rlang::expr({
                rlang::check_dots_unnamed()
                dots <- rlang::dots_list(...)
                content <- !!content_expr
                attribs <- if (is.null(attr)) {
                    !!brackets
                } else {
                    sprintf("{%s}", paste0(attr, collapse = " "))
                }
                output <- sprintf(!!template, content, attribs)
                as_markdown(output, "\n")
            })
        } else {
            rlang::expr({
                rlang::check_dots_unnamed()
                dots <- rlang::dots_list(...)
                content <- !!content_expr
                output <- sprintf(!!template, content)
                as_markdown(output, "\n")
            })
        }
    }

    rlang::new_function(
        args = if (attributes) rlang::exprs(... = , attr = NULL) else rlang::exprs(... = ),
        body = function_body,
        env = asNamespace("quartools")
    )
}
```

**Comment by elipousson** [comment]
I'm hoping the approach I've started on works with what you have in mind. I took your suggestion to combine keys and values into a single parameter but didn't create anything as flexible as the `element_constructor()` function.

To make this easier to consider as a PR, I left all of the existing code in place and switched to using an abbreviation for Quarto (`qto`) as a prefix for all the new functions. I think it works well as a naming convention but open to changes if you have something different in mind. I do think avoiding the namespace conflict posed by the existing `div()` and `span()` would be a good idea.

You can take a look at the branch here: https://github.com/elipousson/quartools/tree/dev

In addition to `qto_callout()` (and the supporting `qto_block()` and `qto_div()`, I've also added support for:

- Shortcodes
- Headings and horizontal rules
- Images per #2 
- Definition lists

I added some basic tests for `qto_block()` and `qto_div()` and I've been trying to add examples as I go so the documentation is not bad. I also added a helper function for rendering the qmd README. Happy to rename this issue to generalize this into a broader discussion re: feature expansion + related refactoring.

**Comment by ElianHugh** [comment]
Thank you, I can see the commits are quite comprehensive -- I'm quite liking the `qto` prefix! I look forward to your PR if you're interested in submitting one. Given the super early stage of the package, I don't really have any compunctions with removing the `div` and `span` functions outright in favour of `qto_div` and `qto_span`.  I think it would be a good idea to rename this issue to reflect the broader scale of the PR.

One thing I've noticed is that the `qto_block` function has a `fence` parameter, presumably to help when fences are deeply nested? From what I can tell, fences are auto-magically nestable due to the presence of attributes, so long as we have the curly brackets, quarto will detect it as a new block[^1] even when nested. i.e, this is a valid block:

```
:::{}
foo
:::
```

as is:

```
:::{}
foo
:::{}
bar
:::
:::

```

---
[^1]:  [Fences without attributes are always closing fences](https://quarto.org/docs/authoring/markdown-basics.html#divs-and-spans)

**Comment by ElianHugh** [comment]
In the same vein as the fence paramter, I've been thinking more broadly about the function signatures of the `qto_div` derivative functions. 

For example, with the `qto_callout` function,  it has a `title` and `heading` parameter, which I think ultimately lead to the same markdown output?  i.e.

```
::: {title = "foo"}

:::

// is the same callout output as

::: {}
# foo
:::
```

That aside, I'm thinking, would it be better to leave the header parameter off entirely? I'm not 100% sold either way, but I think there is something to be said for making the function signature relatively lean. e.g., the same functionality could be achieved via

```r
qto_callout(
	qto_header("I'm a title!"),
	"Some text"
)
```

**Comment by elipousson** [comment]
Good call on `qto_callout()` – I just dropped the heading parameter, fixed a bug in `qto_fig()` that completely broke my code this afternoon, and added a few more functions. I'm going to open up the pull request for review but no rush to dig in. I'm using my own dev branch for a big report at work right now which is where a lot of the new code is coming from.
